[server]
enableCORS = true
enableXsrfProtection = false

[runner]
# This tells Streamlit Cloud where to find the package
pythonPath = "/mount/src/linkedin-chatbot-job-mnt-team"

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501